@echo off
REM A simple batch script made for generating battery reports
color 0A
@echo on
@echo ..........................................................................
@echo .....................         ......................           ...........
@echo ................                   .................     ...     .........
@echo ..............                        ..............   .......    ........
@echo ............            Eh?             .......................   ........
@echo ...........         Hello There,         .......................  ........
@echo ..........          Traveller             .....................   ........
@echo .........                                  ....................   ........
@echo ........     What can I do for you         ..................    .........
@echo ........     today?                         ........            ..........
@echo ........     Oh!                            ........        ..............
@echo ........     A Battery Report, you say?     ........   ...................
@echo ........                                   .........  ....................
@echo .........     Just Press Any Key           ........  .....................
@echo ..........    and I'll be on my way       ................................
@echo ...........   to do that for'ya :)       .................................
@echo ............                            ..................................
@echo .............                         ...........     ....................
@echo ................                    ............      ....................
@echo ....................            ................     .....................
@echo ..........................................................................
@echo.
@echo.
@echo off

REM Battery Report Generator - Hopefully it won't be damaged!

pause
cls
color 0C
@echo........................................
@echo....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.....
@echo....EE...........................EE.....
@echo....E..EEEE.EEEE.EEEE..EEEE.EEEE..E.....
@echo....E..EEEE.EEEE.EEEE..EEEE.EEEE..EEE...
@echo....E..EEEE.EEEE.EEEE..EEEE.EEEE..EEE...
@echo....E..EEEE.EEEE.EEEE..EEEE.EEEE..EEE...
@echo....E..EEEE.EEEE.EEEE..EEEE.EEEE.EEEE...
@echo....E..EEEE.EEEE.EEEE..EEEE.EEEE..E.....
@echo....EE...........................EE.....
@echo....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.....
@echo........................................
@echo.
@echo Initiating Energy Evaluation Process
powercfg -energy -output c:\energy-report.html

pause
cls
color 0A

@echo off
@echo on
@echo ...........................................................................
@echo ...........................................................................
@echo ........           ..........         ......     ....      ..           ...
@echo ........              .....             ...       ...      ..           ...
@echo .......                ...      ..      ...       ...     ...           ...
@echo .......       ..       ..       ..      ...       ..      ..       ........
@echo .......       ..      ...      ..       ...        .      ..       ........
@echo ......       ..       ..       ..       ..         .     ...      .........
@echo ......       ..       ..       ..      ...               ..           .....
@echo ......       ..      ...      ..       ...               ..           .....
@echo ......      ..       ..       ..       ..               ...           .....
@echo .....       ..       ..       ..       ..     ..        ..       ..........
@echo .....       ..       ..      ...      ...     ..        ..       ..........
@echo .....      ..       ..       ..       ..      ..       ...       ..........
@echo ....                ..       .       ...      ..       ..            ......
@echo ....               ....             ....     ...       ..            ......
@echo ....            .........         .....      ...      ...           .......
@echo ...........................................................................
@echo ...........................................................................
@echo.
@echo Opening Folder containing your new energy report...
@echo Last Full Charge / Design Capacity * 100 = True Percentage
@echo off

timeout /T 4 /nobreak

explorer "C:\"

